FROM eclipse-temurin:21-jdk-jammy
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY pom.xml ./
RUN mvn dependency:resolve dependency:resolve-plugins -B
COPY . .
EXPOSE 8081
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
