version: '3.8'

services:
  cassandra:
    image: cassandra:5.0
    ports:
      - "9042:9042"
    volumes:
      - ../../demo/cassandra/init.cql:/docker-entrypoint-initdb.d/init.cql
    environment:
      CASSANDRA_CLUSTER_NAME: dev-cluster
      HEAP_NEWSIZE: 512M
      MAX_HEAP_SIZE: 1024M
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark:
    image: bitnami/spark:3.5.1
    ports:
      - "4040:4040"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no

  spring-app:
    build:
      context: ../../demo
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8081"
    volumes:
      - ../../demo:/app
      - ~/.m2:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      cassandra:
        condition: service_healthy
